# Generated by Django 4.1.3 on 2022-11-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_management', '0002_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(3, '4级'), (4, '4级'), (2, '2级'), (1, '1级')], default=1, verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(2, '未占用'), (1, '已占用')], default=2, verbose_name='当前状态')),
            ],
        ),
    ]
