# Generated by Django 4.1.3 on 2022-11-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_management', '0003_prettyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettyinfo',
            name='level',
            field=models.SmallIntegerField(choices=[(3, '3级'), (2, '2级'), (1, '1级'), (4, '4级')], default=1, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='prettyinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已占用'), (2, '未占用')], default=2, verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
    ]
