# Generated by Django 4.1.3 on 2022-11-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_management', '0004_alter_prettyinfo_level_alter_prettyinfo_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='管理员账户')),
                ('password', models.CharField(max_length=64, verbose_name='管理员密码')),
            ],
        ),
        migrations.AlterField(
            model_name='prettyinfo',
            name='level',
            field=models.SmallIntegerField(choices=[(4, '4级'), (2, '2级'), (1, '1级'), (3, '3级')], default=1, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='prettyinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '未占用'), (1, '已占用')], default=2, verbose_name='当前状态'),
        ),
    ]
